-- Reconciling the database with the schema.
--
-- Found by diffing the migration history against prisma/schema.prisma
-- rather than by anything failing. Drift is silent until somebody
-- regenerates a migration and gets a diff nobody expected.

-- 1. A money column must not have a default.
--
-- vat_minor got DEFAULT 0 so the column could be added NOT NULL to
-- existing rows. Leaving it means an insert that omits the ДДС silently
-- records zero, and a fee that quietly charges no tax is the wrong
-- direction to fail in.
ALTER TABLE "fees" ALTER COLUMN "vat_minor" DROP DEFAULT;

-- 2. Ids are generated by the application, not the database.
--
-- Sixteen tables were already written that way; the two hand-written
-- migrations that added these broke the convention.
ALTER TABLE "sellers"  ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "invoices" ALTER COLUMN "id" DROP DEFAULT;

-- 3. Deleting a recipient must cascade, not null the column.
--
-- outbox_one_recipient requires exactly one of user_id / seller_id. SET
-- NULL — which is what Prisma infers for an optional relation — would
-- leave both null and violate it, so erasing a user would fail on a
-- check constraint. Cascading is also correct on its own terms: a queued
-- message to somebody who no longer exists has nowhere to go.
ALTER TABLE "outbox" DROP CONSTRAINT "outbox_user_id_fkey";
ALTER TABLE "outbox"
  ADD CONSTRAINT "outbox_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
